on: [push, workflow_dispatch]
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
      NO_TEST: true
      NOMAD_VAR_COUNT: 2
      BASE_DOMAIN: ux-b.archive.org
      NOMAD_VAR_HOSTNAMES='["emularity-config"]'
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
