on: [push, workflow_dispatch]
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
      NO_TEST: true
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_TOKEN_PROD: ${{ secrets.NOMAD_TOKEN_PROD }}
